version: '3'

networks:
  rabbitmq_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.7.8
    container_name: RabbitMQ
    networks:
      - rabbitmq_network
    ports:
      - "5672:5672"

  postcard:
    build: ./postcard
    image: claclacla/postcard-js
    container_name: Postcard
    networks:
      - rabbitmq_network 
    volumes:
      - "${APP_FOLDER}:/usr/src/app"
    links:
      - rabbitmq
    tty: true
    stdin_open: true